
spring:
  application:
    name: xiaohashu-auth
  jackson:
#    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev # 默认激活 dev 本地开发环境

server:
  port: 8081

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:mapper/**/*.xml